import type { ThemeConfig } from "../types";

const medicalTheme: ThemeConfig = {
    id: "medical",
    name: "Medical Practice & Healthcare",
    nameFr: "Cabinet Médical & Santé",
    icon: "🏥",
    emoji: "🏥",
    tagline: "Your AI-powered healthcare assistant",
    taglineFr: "Votre assistant IA santé",
    description: "AI tailored for medical practices, clinics, and healthcare providers. Streamline patient communication, generate health content, manage appointments, and reduce administrative burden.",
    descriptionFr: "IA adaptée aux cabinets médicaux, cliniques et professionnels de santé. Simplifiez la communication patient, générez du contenu santé et réduisez la charge administrative.",
    colorPrimary: "#065f46", colorSecondary: "#10b981", colorAccent: "#059669",
    gradientFrom: "from-emerald-900/20", gradientTo: "to-teal-900/10",
    systemPrompt: `You are an AI assistant for {{businessName}}, a medical practice at {{location}}. Dr. {{ownerName}}, specializing in {{specialties}}. Services: {{services}}. Hours: {{operatingHours}}. Communication: {{brandVoice}}. IMPORTANT: You do NOT provide medical diagnoses or prescriptions. All content is for administrative and educational purposes only.`,
    systemPromptFr: `Vous êtes un assistant IA pour {{businessName}}. Dr. {{ownerName}}, spécialiste en {{specialties}}. IMPORTANT: Vous ne fournissez PAS de diagnostics médicaux.`,
    dataFields: [
        { key: "businessName", label: "Practice Name", labelFr: "Nom du cabinet", type: "text", placeholder: "e.g. Centre Médical Saint-Honoré", required: true, group: "business" },
        { key: "ownerName", label: "Lead Physician", labelFr: "Médecin principal", type: "text", placeholder: "e.g. Dr. Marie Laurent", required: true, group: "business" },
        { key: "location", label: "Address", labelFr: "Adresse", type: "text", placeholder: "e.g. 8 Avenue de l'Opéra, Paris", required: true, group: "business" },
        { key: "phone", label: "Phone", labelFr: "Téléphone", type: "text", placeholder: "+33 1 44 50 00 00", group: "business" },
        { key: "email", label: "Email", labelFr: "Email", type: "text", group: "business" },
        { key: "operatingHours", label: "Consultation Hours", labelFr: "Horaires de consultation", type: "textarea", placeholder: "Mon-Fri 8:30-18:00, Sat 9:00-12:00", group: "business" },
        { key: "specialties", label: "Medical Specialties", labelFr: "Spécialités médicales", type: "textarea", placeholder: "General Practice, Dermatology, Pediatrics...", required: true, group: "services" },
        { key: "services", label: "Services Offered", labelFr: "Services proposés", type: "textarea", placeholder: "General consultations, vaccinations, health check-ups, minor procedures...", required: true, group: "services" },
        { key: "teamMembers", label: "Medical Team", labelFr: "Équipe médicale", type: "textarea", placeholder: "Dr. Laurent - GP\nDr. Petit - Dermatologist\nNurse Sophie Martin", group: "services" },
        { key: "insuranceAccepted", label: "Insurance / Conventions", labelFr: "Conventions / Mutuelles", type: "textarea", placeholder: "Secteur 1, Carte Vitale, All major mutual funds...", group: "services" },
        { key: "brandVoice", label: "Communication Style", labelFr: "Style de communication", type: "select", options: ["Warm & Reassuring", "Professional & Clinical", "Friendly & Accessible"], group: "brand" },
        { key: "policies", label: "Practice Policies", labelFr: "Politiques du cabinet", type: "textarea", placeholder: "24h cancellation notice, online booking via Doctolib...", group: "advanced" },
    ],
    quickActions: [
        { id: "patient-reminder", label: "Appointment Reminder", labelFr: "Rappel de rendez-vous", icon: "📅", promptTemplate: "Draft a {{brandVoice}} appointment reminder message from {{businessName}} (Dr. {{ownerName}}). Include: date/time placeholder, preparation instructions, address: {{location}}, phone: {{phone}}.", category: "communication" },
        { id: "health-post", label: "Health Education Post", labelFr: "Post éducation santé", icon: "🩺", promptTemplate: "Write an educational social media post from {{businessName}} about a common health topic related to {{specialties}}. Make it accessible, accurate, and include a CTA to book a consultation. Tone: {{brandVoice}}.", category: "content" },
        { id: "referral-letter", label: "Draft Referral Letter", labelFr: "Lettre d'orientation", icon: "📝", promptTemplate: "Draft a professional medical referral letter template from Dr. {{ownerName}} at {{businessName}}. Include: patient info placeholders, reason for referral, relevant medical history section, and requested investigation.", category: "document" },
        { id: "follow-up", label: "Patient Follow-Up", labelFr: "Suivi patient", icon: "💬", promptTemplate: "Draft a {{brandVoice}} patient follow-up email from {{businessName}}. Thank them for their visit, summarize generic post-visit instructions, and provide contact info: {{phone}}, {{email}}.", category: "communication" },
        { id: "faq", label: "Generate Patient FAQ", labelFr: "FAQ patients", icon: "❓", promptTemplate: "Create a comprehensive FAQ page for {{businessName}}'s website. Specialties: {{specialties}}. Cover: appointment booking, insurance ({{insuranceAccepted}}), hours ({{operatingHours}}), emergency procedures, and preparation for visits.", category: "content" },
    ],
    contentTemplates: [
        { id: "wellness-newsletter", name: "Monthly Wellness Newsletter", nameFr: "Newsletter bien-être", category: "email", icon: "📧", promptTemplate: "Draft a monthly wellness newsletter for {{businessName}}'s patients. Include: seasonal health tips related to {{specialties}}, practice news, and vaccination reminders." },
        { id: "consent-form", name: "Informed Consent Template", nameFr: "Formulaire de consentement", category: "document", icon: "📄", promptTemplate: "Create an informed consent form template for {{businessName}}. Include: procedure description placeholder, risks, benefits, alternatives, and patient signature section." },
    ],
    agents: [
        { id: "patient-comms", name: "Patient Communications", nameFr: "Communication patients", role: "Draft patient messages", icon: "💬", systemPrompt: "You handle patient communications for {{businessName}}. Always {{brandVoice}}. Never provide medical advice." },
        { id: "health-content", name: "Health Content Creator", nameFr: "Créateur de contenu santé", role: "Create health education content", icon: "📚", systemPrompt: "You create accurate health education content for {{businessName}}, specializing in {{specialties}}. Always cite evidence-based information." },
    ],
    phase: 1, category: "Healthcare", keywords: ["medical", "doctor", "health", "clinic", "médecin", "santé", "cabinet"],
    targetAudience: "Doctors, dentists, therapists, clinics, healthcare providers",
    sampleData: {
        businessName: "Centre Médical Saint-Honoré",
        ownerName: "Dr. Marie Laurent",
        location: "8 Avenue de l'Opéra, 75001 Paris",
        phone: "+33 1 44 50 00 00",
        email: "contact@cm-sthonore.fr",
        operatingHours: "Monday–Friday 8:30–18:00\nSaturday 9:00–12:00\nEmergencies: SOS Médecins referral",
        specialties: "General Practice, Dermatology, Pediatrics, Sports Medicine",
        services: "General consultations, Skin screenings, Child health check-ups, Sports injury assessment, Vaccinations, Minor surgical procedures, Health certificates",
        teamMembers: "Dr. Marie Laurent - General Practice\nDr. Thomas Petit - Dermatology\nDr. Julie Moreau - Pediatrics\nSophie Martin - Practice Nurse",
        insuranceAccepted: "Secteur 1 (conventionné), Carte Vitale, All major mutuelles, MGEN, Harmonie",
        brandVoice: "Warm & Reassuring",
        policies: "Online booking via Doctolib, 24h cancellation notice required, Walk-ins accepted for emergencies only",
    },
};

export default medicalTheme;
